services:
  - type: web
    name: face-login-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn auth_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: auth_backend.settings
      - key: SECRET_KEY
        value: your_django_secret_key
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
